# SETUP
baseurl = "https://ttntm.github.io"
publishdir = "ttntm.github.io"
DefaultContentLanguage = "en"
canonifyUrls = "true"
googleAnalytics = ""
# pygmentsUseClasses = "true"
PygmentsCodeFences = true
PygmentsStyle = "tango"

[params]
    year = "2019"
    author = "ttntm"
    title = "Tom's Journal & Blog | ttntm"
    description = "A journal/blog about web design, IT and related topics."
    DateForm = "02.01.2006"
    showReadTime = 1
    showProjects = "false"

[[params.social]]
    title = "Twitter"
    icon = "twitter"
    url = "https://twitter.com/thet0m"
[[params.social]]
    title = "GitHub"
    icon = "github"
    url = "https://github.com/ttntm"
[[params.social]]
    title = "CodePen"
    icon = "codepen"
    url = "https://codepen.io/ttntm/"
# [[params.social]]
    # title = "freeCodeCamp"
    # icon = "free-code-camp"
    # url = "https://www.freecodecamp.org/ttntm"

# BLOG
paginate = 3
paginatePath = "page"

[permalinks] 
blog = "blog/:slug/"

[params.pagination]
    # These are all optional and default to true
    class = "justify-content-center mt-3 mb-4"      # Add classes to the nav element
    showBeginEnd = false       # If false it will hide the First/Previous/Next/Last if it evaluates to false
    showFirst = false          # If false it will hide the First page nav button
    firstIndicator = "<i class='fas fa-long-arrow-alt-left'></i>"       # Change the default indicator to something else, like "First" or an icon wrapped in an i element
    # showPrevious = true       # If false it will hide the previous button
    previousIndicator = "<i class='fas fa-chevron-left'></i>"    # Change the default indicator to something else, like "Previous" or an icon wrapped in an i element
    # showNext = true           # True by default - Only "false" will hide the next button
    nextIndicator = "<i class='fas fa-chevron-right'></i>"        # Change the default indicator to something else, like "Next" or an icon wrapped in an i element
    showLast = false           
    lastIndicator = "<i class='fas fa-long-arrow-alt-right'></i>"        
    # showPageNumbers = true    # If false it will hide the numbering of pages
    # pagesBetweenActive = 2    # How many page numbers to show between the active page - it defaults to 3